name: cryptoplease_ui
description: A new flutter plugin project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  dfunc: ^0.7.2
  flutter:
    sdk: flutter
  provider: ^6.0.0
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mews_pedantic: ^0.6.0
