include: package:mews_pedantic/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.mocks.dart"
    - "test/generated/**"
    - "lib/gen/**"

  errors:
    deprecated_member_use_from_same_package: ignore

dart_code_metrics:
  rules-exclude:
    - "**/*.gr.dart"
