name: cryptoplease
description: CryptoPlease mobile wallet for Solana
publish_to: "none"
version: 1.40.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^4.2.1
  bip39: ^1.0.6
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.1.0
  collection: ^1.15.0
  cryptoplease_api:
    path: ../cryptoplease_link/cryptoplease_api/
  cryptoplease_ui:
    path: ../cryptoplease_ui/
  date_time_format: ^2.0.1
  decimal: ^2.2.0
  dfunc: ^0.8.0+1
  dio: ^4.0.0
  drift: ^1.5.0
  fast_immutable_collections: ^7.4.1
  firebase_analytics: ^9.3.0
  firebase_core: ^1.20.0
  firebase_dynamic_links: ^4.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.6
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3
  flutter_svg_provider: ^1.0.3
  freezed_annotation: ^2.1.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  json_annotation: ^4.4.0
  jupiter_aggregator: ^1.0.0
  logging: ^1.0.2
  meta: ^1.7.0
  mews_pedantic: ^0.7.0
  nested: ^1.0.0
  package_info_plus: ^1.3.0
  path: ^1.8.0
  path_provider: ^2.0.2
  provider: ^6.0.0
  qr_code_scanner:
    git:
      url: https://github.com/xeinebiu/qr_code_scanner.git
      ref: fix_break_changes_platform
  qr_flutter: ^4.0.0
  retrofit: ^3.0.1
  rxdart: ^0.27.1
  sentry_flutter: ^6.9.0
  share: ^2.0.4
  shared_preferences: ^2.0.15
  solana:
    path: ../solana/
  sqlite3_flutter_libs: ^0.5.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.12
  uuid: ^3.0.4

dev_dependencies:
  auto_route_generator: ^4.2.0
  bloc_test: ^9.0.3
  build_runner: ^2.2.0
  drift_dev: ^1.5.2
  flutter_driver:
    sdk: flutter
  flutter_gen_runner: ^4.1.5
  flutter_native_splash: ^2.2.7
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  golden_toolkit: ^0.13.0
  http: ^0.13.4
  integration_test:
    sdk: flutter
  json_serializable: ^6.1.4
  mockito: ^5.3.0
  recase: ^4.0.0
  retrofit_generator: ^4.0.0

dependency_overrides:
  qr_code_scanner:
    git:
      url: https://github.com/X-SLAYER/qr_code_scanner.git
      ref: flutter-beta

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/markdowns/
  fonts:
    - family: Roboto
      fonts:
      - asset: packages/cryptoplease_ui/fonts/Roboto-Thin.ttf
        weight: 100
      - asset: packages/cryptoplease_ui/fonts/Roboto-ThinItalic.ttf
        style: italic
        weight: 100
      - asset: packages/cryptoplease_ui/fonts/Roboto-Light.ttf
        weight: 300
      - asset: packages/cryptoplease_ui/fonts/Roboto-LightItalic.ttf
        style: italic
        weight: 300
      - asset: packages/cryptoplease_ui/fonts/Roboto-Regular.ttf
        weight: 400
      - asset: packages/cryptoplease_ui/fonts/Roboto-Italic.ttf
        style: italic
        weight: 400
      - asset: packages/cryptoplease_ui/fonts/Roboto-Medium.ttf
        weight: 500
      - asset: packages/cryptoplease_ui/fonts/Roboto-MediumItalic.ttf
        style: italic
        weight: 500
      - asset: packages/cryptoplease_ui/fonts/Roboto-Bold.ttf
        weight: 700
      - asset: packages/cryptoplease_ui/fonts/Roboto-BoldItalic.ttf
        style: italic
        weight: 700
      - asset: packages/cryptoplease_ui/fonts/Roboto-Black.ttf
        weight: 900
      - asset: packages/cryptoplease_ui/fonts/Roboto-BlackItalic.ttf
        style: italic
        weight: 900

flutter_native_splash:
  color: "#f46640"
