name: solana_dart
version: 0.1.4
repository: https://github.com/antoineherzog/dart-solana-lib
description: >-
  Simple library to interact with the Solana blockchain
environment:
  sdk: '>=2.10.5 <3.0.0'
dependencies:
  http: ^0.12.2
  bip39: ^1.0.3
  cryptography: ^1.4.1
  convert: ^2.1.1
  meta: ^1.2.4
  json_annotation: ^3.1.1
  bip32: ^1.0.8

dev_dependencies:
  test: ^1.15.7

