name: solana_mobile_wallet
description: A reference implementation of the Mobile Wallet Adapter specification for Flutter.
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mews_pedantic: ^0.7.0
  pigeon: ^3.2.6

flutter:
  plugin:
    platforms:
      android:
        package: com.solana.solana_mobile_wallet
        pluginClass: SmsWalletPlugin
