name: sms_wallet_example
description: Demonstrates how to use the sms_wallet plugin.
publish_to: "none"

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.1.0
  sms_wallet:
    path: ../
  solana: ^0.26.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  mews_pedantic: ^0.7.0

flutter:
  uses-material-design: true
