name: scalex_api
description: A client for Scalex API
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  convert: ^3.1.1
  crypto: ^3.0.3
  dio: ^4.0.6
  freezed_annotation: ^2.4.1
  retrofit: ^3.3.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mews_pedantic: ^0.20.0
  retrofit_generator: ^4.2.0
