name: share_escrow
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  borsh: ^0.3.1+2
  borsh_annotation: ^0.3.1+3
  solana: ^0.29.0

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.2
  mews_pedantic: ^0.13.0
  test: ^1.22.1