name: espressocash_app
description: Espresso Cash mobile wallet for Solana
publish_to: "none"
version: 1.68.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  async: ^2.10.0
  auto_route: ^6.0.5
  bip39: ^1.0.6
  bloc_concurrency: ^0.2.1
  cached_network_image: ^3.2.3
  collection: ^1.17.0
  date_time_format: ^2.0.1
  decimal: ^2.3.2
  dfunc: ^0.8.1
  dio: ^4.0.6
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_db_store: ^5.1.0
  drift: ^2.6.0
  espressocash_api:
    path: ../espressocash_backend/espressocash_api/
  fast_immutable_collections: ^9.0.0
  firebase_analytics: ^10.2.0
  firebase_app_installations: ^0.2.2
  firebase_core: ^2.9.0
  firebase_dynamic_links: ^5.1.0
  firebase_remote_config: ^4.0.0
  fl_chart: ^0.61.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  http: ^0.13.5
  image_picker: ^0.8.7+1
  injectable: ^2.1.1
  intercom_flutter: ^7.6.8
  intl: ^0.17.0
  json_annotation: ^4.8.0
  localizely_sdk: ^2.5.1
  logging: ^1.1.1
  meta: ^1.8.0
  mews_pedantic: ^0.13.0
  mobile_scanner: ^3.2.0
  nested: ^1.0.0
  package_info_plus: ^3.0.3
  path: ^1.8.2
  path_provider: ^2.0.14
  provider: ^6.0.5
  qr_flutter: ^4.0.0
  ramp_flutter: ^1.0.1
  retrofit: ^3.3.1
  rive: ^0.10.3
  rxdart: ^0.27.7
  sentry_flutter: ^7.4.1
  share: ^2.0.4
  shared_preferences: ^2.1.0
  sliver_tools: ^0.2.9
  solana:
    path: ../solana/
  solana_seed_vault:
    path: ../solana_seed_vault/
  sqlite3_flutter_libs: ^0.5.13
  storybook_flutter: ^0.12.0
  uni_links: ^0.5.1
  uuid: ^3.0.7
  webview_flutter: ^4.0.7

dev_dependencies:
  auto_route_generator: ^6.0.0
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  drift_dev: ^2.6.0
  flutter_driver:
    sdk: flutter
  flutter_gen_runner: ^5.2.0
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  golden_toolkit: ^0.15.0
  injectable_generator: ^2.1.5
  integration_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mockito: ^5.4.0
  recase: ^4.1.0
  retrofit_generator: ^4.2.0

flutter_gen:
  integrations:
    flutter_svg: true
    rive: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/rive/

  fonts:
    - family: RobotoApp
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          style: italic
          weight: 900

flutter_native_splash:
  color: "#f46640"
