name: wallet_example
description: Demonstrates how to use the solana_seed_vault plugin for wallets

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  solana_seed_vault:
    path: ../
  freezed_annotation: ^2.2.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  dfunc: ^0.8.0+1
  request_permission: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  freezed: ^2.2.0
  mews_pedantic: ^0.10.0

flutter:
  uses-material-design: true
