name: Check PR to master

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      DEVNET_RPC_URL: "http://solana:8899"
      DEVNET_WEBSOCKET_URL: "ws://solana:8900"
    container:
      image: google/dart:latest
    services:
      solana:
        image: ookamikb/solana-test-validator:latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      - run: dart pub global activate melos
      - run: melos run check_master
