name: Check PR to master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    services:
      solana:
        image: iharob/solana:latest
        ports:
          - 8899:8899
    container: google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: dart tests
        run: pub run test
