name: Check PR (libs)

on:
  pull_request:
    branches:
      - master
    paths:
      - "packages/**"
      - "!packages/cryptoplease/**"
      - "!packages/cryptoplease_ui/**"
      - "!packages/cryptoplease_link/**"
  push:
    branches:
      - master
    paths:
      - "packages/solana/**"

concurrency:
  group: ref-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check_pr_libs:
    strategy:
      matrix:
        solanaVersion: ["stable", "beta"]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    env:
      DEVNET_RPC_URL: "http://solana:8899"
      DEVNET_WEBSOCKET_URL: "ws://solana:8900"
    container:
      image: ghcr.io/cryptoplease/flutter:3.0.0
    services:
      solana:
        image: solanalabs/solana:${{ matrix.solanaVersion }}
        options: --entrypoint="solana-test-validator"
    steps:
      - uses: actions/checkout@v2
      - run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      - run: dart pub global activate remove_from_coverage
      - run: make libs_check_formatting
      - run: make libs_analyze
      - run: make libs_test
      - run: make libs_coverage
      - uses: codecov/codecov-action@v2
