name: Run E2E tests
on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref }}-e2e
  cancel-in-progress: true

jobs:
  e2e:
    permissions:
      contents: write
      packages: read
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cryptoplease/flutter:2.10.3
    steps:
      - uses: actions/checkout@v2
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          project_id: "cryptoplease-dev"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - run: make app_get
      - run: make app_build
      
      - name: 'Run E2E tests'
        run: make firebase_e2e
        working-directory: packages/cryptoplease
