name: espressocash_common
description: Espresso Cash Common Library
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  decimal: ^2.3.3
  dfunc: ^0.9.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  meta: ^1.10.0
  solana:
    path: ../solana/

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mews_pedantic: ^0.25.0
